### ISSUE TITLE
Sort station names lexicographically 

### ISSUE THREAD

**Issue by avipars** [sh0oki/israel-rail-api#7]
Is it possible to sort the station names lexicographically (preferably in Hebrew and English at least)

![image](https://github.com/user-attachments/assets/453bc763-ca7f-4429-bb68-ceaf6aff45a8)

This is using your API indirectly (via home-assistant integration), the drop down menu appears to not be ordered in any meaningful way which makes it difficult for someone to find a specific station.

**Comment by sh0oki** [comment]
Hey @avipars :) this seems to be related to the use of home-assistant, as this package doesn't really aim to give the list of stations. 
I went ahead and opened a PR in their repo as this seemed interesting

**Comment by sh0oki** [comment]
Hey @avipars, seems like this was merged into home-assistant. Closing for now, LMK if this works!

**Comment by avipars** [comment]
Thanks! Seems good by me

**Comment by itamar499** [comment]
בימים האחרונים חוזרת לי שגיאת 403. יודע מה העניין?
